spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: springcloud-config-eureka-server-dev
server:
  port: 7004
eureka:
  instance:
    hostname: eureka7001.com  
  client:
    register-with-eureka: false     
    fetch-registry: false           
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
spring:
    profiles: test
    application:
        name: springcloud-config-eureka-server-test
server:
  port: 7005
eureka:
  instance:
    hostname: eureka7001.com  
  client:
    register-with-eureka: false     
    fetch-registry: false           
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    