spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.hzit.api.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/bj1901
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka 
  instance: 
    instance-id: springcloud-dept:8001  
    prefer-ip-address: true        
info:                              
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8002
mybatis:
  type-aliases-package: com.hzit.api.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: springcloud-config-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/bj1901_2
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7005/eureka 
  instance: 
    instance-id: springcloud-dept:8001  
    prefer-ip-address: true        
info:                              
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$